MyAutoService/Pages/Cars/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyAutoService.Data;
using MyAutoService.Model;

namespace MyAutoService.Pages.Cars
{
    public class CreateModel : PageModel
    {
        private readonly MyAutoService.Data.ApplicationDbContext _context;

        public CreateModel(MyAutoService.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Car Car { get; set; }

        public IActionResult OnGet(string userId = null)
        {
            Car = new Car();
            if (userId==null)
            {
                var ClaimIdentity = (ClaimsIdentity)User.Identity;
                var Claim = ClaimIdentity.FindFirst(ClaimTypes.NameIdentifier);
                userId = Claim.Value;
            }

            Car.UserId = userId;

            return Page();
        }

        [BindProperty]
        public IFormFile ImgUp { get; set; }


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (ImgUp != null)
            {
                Car.ImageName = Guid.NewGuid().ToString() + Path.GetExtension(ImgUp.FileName);
                string savePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/CarImages", Car.ImageName);
                using (var fileStream = new FileStream(savePath, FileMode.Create))
                {
                    ImgUp.CopyTo(fileStream);
                }
            }
            _context.Cars.Add(Car);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

MyAutoService/Pages/ServiceTypes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyAutoService.Model;
using MyAutoService.Data;
using Microsoft.AspNetCore.Authorization;
using MyAutoService.Utlities;

namespace MyAutoService.Pages.ServiceTypes
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class CreateModel : PageModel
    {

        private ApplicationDbContext _dbcontext;

        public CreateModel(ApplicationDbContext dbcontext)
        {
            _dbcontext = dbcontext;
        }

        public ServiceType ServiceType { get; set; }

        public IActionResult OnGet()
        {
            
            return Page();
        }

        public async Task<IActionResult> OnPost(ServiceType serviceType)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _dbcontext.ServiceType.Add(serviceType);
             await _dbcontext.SaveChangesAsync();
            return RedirectToPage("Index");

        }

    }
}

MyAutoService/Pages/ServiceTypes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyAutoService.Data;
using MyAutoService.Model;
using MyAutoService.Utlities;

namespace MyAutoService.Pages.ServiceTypes
{

    [Authorize(Roles = SD.AdminEndUser)]
    public class DetailsModel : PageModel
    {
        private readonly MyAutoService.Data.ApplicationDbContext _context;

        public DetailsModel(MyAutoService.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public ServiceType ServiceType { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ServiceType = await _context.ServiceType.FirstOrDefaultAsync(m => m.Id == id);

            if (ServiceType == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

MyAutoService/Pages/Services/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyAutoService.Data;
using MyAutoService.Model;
using MyAutoService.Model.ViewModels;

namespace MyAutoService.Pages.Services
{
    public class CreateModel : PageModel
    {
        private ApplicationDbContext _db;

        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public CarsServiceViewModel CarServiceVM { get; set; }


        public async Task<IActionResult> OnGet(int carId)
        {
            CarServiceVM = new CarsServiceViewModel()
            {
                Car = await _db.Cars.Include(m => m.ApplicationUser).FirstOrDefaultAsync(m => m.Id == carId),
                ServiceHeader = new ServiceHeader()
            };

            List<string> lstServiceTypeInShoppingCart = _db.ServicesShoppingCarts
                .Include(c => c.ServiceType)
                .Where(c => c.CarId == carId)
                .Select(c => c.ServiceType.Name).ToList();
                

            IQueryable<ServiceType> lstServices = from s in _db.ServiceType
                                                  where !(lstServiceTypeInShoppingCart.Contains(s.Name))
                                                  select s;

            CarServiceVM.ServiceTypesList = lstServices.ToList();

            CarServiceVM.ServicesShoppingCarts = _db.ServicesShoppingCarts.Include(m => m.ServiceType)
                .Where(c => c.CarId == carId).ToList();

            CarServiceVM.ServiceHeader.TotalPrice = 0;

            foreach (var item in CarServiceVM.ServicesShoppingCarts)
            {
                CarServiceVM.ServiceHeader.TotalPrice += item.ServiceType.Price;
            }
            
            return Page();
        }


        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                CarServiceVM.ServiceHeader.DateAdded = DateTime.Now;

                CarServiceVM.ServicesShoppingCarts = _db.ServicesShoppingCarts.Include(c => c.ServiceType)
                    .Where(c => c.CarId == CarServiceVM.Car.Id).ToList();

                foreach (var shop in CarServiceVM.ServicesShoppingCarts)
                {
                    CarServiceVM.ServiceHeader.TotalPrice += shop.ServiceType.Price;
                }

                CarServiceVM.ServiceHeader.CarId = CarServiceVM.Car.Id;
                _db.ServiceHeaders.Add(CarServiceVM.ServiceHeader);
                await _db.SaveChangesAsync();

                foreach (var shop in CarServiceVM.ServicesShoppingCarts)
                {
                    ServiceDetails details = new ServiceDetails()
                    {
                        ServiceHeaderId = CarServiceVM.ServiceHeader.Id,
                        ServiceName = shop.ServiceType.Name,
                        ServicePrice = shop.ServiceType.Price,
                        ServiceTypeId = shop.ServiceTypeId
                    };
                    _db.ServiceDetails.Add(details);
                }
                _db.ServicesShoppingCarts.RemoveRange(CarServiceVM.ServicesShoppingCarts);
                await _db.SaveChangesAsync();
                return RedirectToPage("/Cars/Index", new { userId = CarServiceVM.Car.UserId });
            }


            return Page();
        }


        public async Task<IActionResult> OnPostAddToCart()
        {
            ServicesShoppingCart Shopping = new ServicesShoppingCart()
            {
                CarId = CarServiceVM.Car.Id,
                ServiceTypeId=CarServiceVM.ServiceDetails.ServiceTypeId
            };
            _db.ServicesShoppingCarts.Add(Shopping);
            await _db.SaveChangesAsync();

            return RedirectToPage("Create", new { carId = CarServiceVM.Car.Id });
        }


        public async Task<IActionResult> OnPostRemoveFromCart(int serviceTypeId)
        {
            ServicesShoppingCart shopping = _db.ServicesShoppingCarts
                .First(u => u.CarId == CarServiceVM.Car.Id && u.ServiceTypeId == serviceTypeId);

            _db.Remove(shopping);

            await _db.SaveChangesAsync();

            return RedirectToPage("Create", new { carId = CarServiceVM.Car.Id });
        }
    }
}

MyAutoService/Pages/Services/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyAutoService.Data;
using MyAutoService.Model;

namespace MyAutoService.Pages.Services
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private ApplicationDbContext _db;

        public DetailsModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public ServiceHeader ServiceHeader { get; set; }

        public List<ServiceDetails> serviceDetails { get; set; }

        public IActionResult OnGet(int serviceid)
        {
            ServiceHeader = _db.ServiceHeaders
                .Include(s => s.Car)
                .Include(s => s.Car.ApplicationUser)
                .FirstOrDefault(s => s.Id == serviceid);

            if (ServiceHeader == null)
                return NotFound();

            serviceDetails = _db.ServiceDetails.Where(d => d.ServiceHeaderId == serviceid).ToList();

            return Page();
        }
    }
}

MyAutoService/Pages/Services/History.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyAutoService.Data;
using MyAutoService.Model;

namespace MyAutoService.Pages.Services
{
    [Authorize]
    public class HistoryModel : PageModel
    {

        private ApplicationDbContext _db;

        public HistoryModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public List<ServiceHeader> serviceHeaders { get; set; }

        public string   UserId { get; set; }
        public void OnGet(int carId)
        {
            serviceHeaders = _db.ServiceHeaders
                .Include(c => c.Car)
                .Include(c => c.Car.ApplicationUser)
                .Where(c => c.CarId == carId).ToList();

            UserId = _db.Cars.Where(c => c.Id == carId).FirstOrDefault().UserId;

        }
    }
}

MyAutoService/Pages/Users/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyAutoService.Model;

namespace MyAutoService.Pages.Users
{
    public class DetailsModel : PageModel
    {
        private readonly MyAutoService.Data.ApplicationDbContext _context;

        public DetailsModel(MyAutoService.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public ApplicationUser ApplicationUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser = await _context.ApplicationUsers.FirstOrDefaultAsync(m => m.Id==id);

            if (ApplicationUser == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

MyAutoService/Pages/Services/Create.cshtml
@page
@model MyAutoService.Pages.Services.CreateModel
@{
    ViewData["Title"] = "سرویس جدید";
}

<div class="container pt-4 pb-2 row">
    <div class="col-6">
        <h2 class="text-info py-2">افزودن سرویس جدید</h2>
    </div>
    <div class="col-6 text-right">
        <a asp-page="/Cars/index" asp-route-userId="@Model.CarServiceVM.Car.UserId" class="btn btn-outline-success form-control">بازگشت به لیست</a>
    </div>
</div>

<div class="container">
    <div class="card">
        <div class="card-header bg-dark text-light ml-0 row container">
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="fas fa-user fa-2x"></i>
            </div>
            <div class="col-5">
                <label class="text-info">
                    @Model.CarServiceVM.Car.ApplicationUser.Name
                </label><br />
                <label class="text-info">
                    @Model.CarServiceVM.Car.ApplicationUser.Email
                </label>
            </div>
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="fas fa-car fa-2x"></i>
            </div>
            <div class="col-5 text-left">
                <label class="text-info">
                    @Model.CarServiceVM.Car.Name @Model.CarServiceVM.Car.Model
                </label><br />
                <label class="text-info">
                    @Model.CarServiceVM.Car.Year @Model.CarServiceVM.Car.Color
                </label>
            </div>

        </div>
        <div class="card-body">
            <form method="post" style="width: 100%">
                <div class="container">
                    <input hidden asp-for="CarServiceVM.Car.Model" />
                    <input hidden asp-for="CarServiceVM.Car.Id" />
                    <input hidden asp-for="CarServiceVM.Car.UserId" />
                    <input hidden asp-for="CarServiceVM.Car.Model" />
                    <input hidden asp-for="CarServiceVM.Car.Name" />
                    <input hidden asp-for="CarServiceVM.Car.Year" />
                    <div class="border rounded p-2">
                        <div class="row">
                            <div class="col-3">
                                <h2 class="text-info pl-3 p2-2 pb-1">سرویس جدید</h2>
                            </div>
                            <div class="col-9 pb-1 pt-2">
                                <div class="row">
                                    <div class="col-8">
                                        <select asp-for="CarServiceVM.ServiceDetails.ServiceTypeId"
                                                class="form-control"
                                                asp-items="@(new SelectList(Model.CarServiceVM.ServiceTypesList,"Id","Name"))">

                                        </select>
                                    </div>
                                    <div class="col-4">
                                        <input type="submit" asp-page-handler="AddToCart" class="form-control btn btn-primary" value="افزودن" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="border container rounded p-2">
                        <h3 class="text-info pb-2">شرح سرویس ها</h3>
                        @if (Model.CarServiceVM.ServicesShoppingCarts.Count == 0)
                        {
                            <p>سرویسی وجود ندارد</p>
                        }
                        else
                        {
                            <div class="row mt-3">
                                <div class="col-7">
                                    <table class="table table-striped border">
                                        <tr class="table-secondary">
                                            <th>@Html.DisplayNameFor(m => Model.CarServiceVM.ServiceTypesList.FirstOrDefault().Name)</th>
                                            <th>@Html.DisplayNameFor(m => Model.CarServiceVM.ServiceTypesList.FirstOrDefault().Price)</th>
                                            <th></th>
                                        </tr>
                                        @foreach (var item in Model.CarServiceVM.ServicesShoppingCarts)
                                        {
                                            <tr>
                                                <td>
                                                    @item.ServiceType.Name
                                                </td>
                                                <td>@item.ServiceType.Price</td>
                                                <td>
                                                    <button type="submit"
                                                            asp-page-handler="RemoveFromCart"
                                                            asp-route-serviceTypeId="@item.ServiceTypeId"
                                                            class="btn btn-danger form-control">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        }
                                        <tr style="background-color: #e2fee2">
                                            <td colspan="1" class="text-success">
                                                جمع کل :
                                            </td>
                                            <td colspan="2">
                                                @Model.CarServiceVM.ServiceHeader.TotalPrice.ToString("#,0 تومان")
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="col-5 px-4 pb-2">
                                    <div class="row ">
                                        <div class="col-3 p-0">
                                            <label asp-for="CarServiceVM.ServiceHeader.Miles"
                                                   class="form-control" style="border: none"></label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="CarServiceVM.ServiceHeader.Miles"
                                                   class="form-control" id="txtMiles" />
                                        </div>
                                    </div>
                                    <div class="row py-2">
                                        <div class="col-12">
                                            <textarea placeholder="توضیحات" asp-for="CarServiceVM.ServiceHeader.Description"
                                                      class="form-control" style="height: 100px"></textarea>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12">
                                            <button  onclick="return validateInput()"  class="btn btn-success form-control">
                                                ثبت سرویس
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        function validateInput() {
            var miles = document.getElementById("txtMiles").value;
            if (miles < 1) {
                swal("خطا !", "کیلومتر را وارد کنید","error");
                return false;
            }
        }
    </script>
}

MyAutoService/Pages/Services/Details.cshtml
@page
@model MyAutoService.Pages.Services.DetailsModel
@{
}
<div class="container pt-4 pb-2 row border">
    <div class="col-6">
        <h2 class="text-info py-2">جزئیات سرویس</h2>
    </div>
    <div class="col-3 offset-3 text-right py-2">
        <a asp-page="/Services/History" asp-route-carId="@Model.ServiceHeader.CarId" class="btn btn-outline-success form-control">
            بازگشت به لیست
        </a>
    </div>
</div>

<div class="container pt-5">
    <div class="card">
        <div class="card-header bg-dark text-light ml-0 row container">
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="fas fa-user"></i>
            </div>
            <div class="col-5">
                <label class="text-info">
                    @Model.ServiceHeader.Car.ApplicationUser.Name
                </label>
                <br />
                <label class="text-info">
                    @Model.ServiceHeader.Car.ApplicationUser.Email / @Model.ServiceHeader.Car.ApplicationUser.PhoneNumber
                </label>
            </div>
            <div class="col-5">
                <label class="text-info">
                    @Model.ServiceHeader.Car.Model / @Model.ServiceHeader.Car.Color
                </label>
                <br />
                <label class="text-info">
                    @Model.ServiceHeader.Car.Name
                </label>
            </div>
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="fas fa-car"></i>
            </div>
        </div>
        <div class="card-body">
            <div class="row pt-3">
                <div class="col-5 px-4 pb-2">
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="ServiceHeader.Miles" class="form-control" style="border: none"></label>
                        </div>
                        <div class="col-9">
                            <input asp-for="ServiceHeader.Miles" readonly class="form-control" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <textarea asp-for="ServiceHeader.Description" readonly class="form-control"></textarea>
                        </div>
                    </div>
                </div>
                <div class="col-7">
                    <table class="table table-striped border">
                        <tr class="table-secondary">
                            <th>
                                @Html.DisplayNameFor(m => m.serviceDetails[0].ServiceName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(m => m.serviceDetails[0].ServicePrice)
                            </th>
                        </tr>
                        @foreach (var item in Model.serviceDetails)
                        {
                            <tr>
                                <td>@item.ServiceName</td>
                                <td class="text-success">@item.ServicePrice.ToString("#,0 تومان")</td>

                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

MyAutoService/Pages/Services/History.cshtml
@page
@model MyAutoService.Pages.Services.HistoryModel
@{
}
<div class="container pt-4 pb-2 row border">
    <div class="col-6">
        <h2 class="text-info py-2">تاریخچه سرویس ها</h2>
    </div>
    <div class="col-3 offset-3 text-right py-2">
        <a asp-page="/Cars/Index" asp-route-userId="@Model.UserId" class="btn btn-outline-success form-control">
            بازگشت به لیست
        </a>
    </div>
</div>

@if (Model.serviceHeaders.Count == 0)
{
    <div class="alert alert-info">
        تاریخچه ای وجود ندارد .
    </div>
}
else
{
    <div class="container pt-5">
        <div class="card">
            <div class="card-header bg-dark text-light ml-0 row container">
                <div class="col-1 text-center pt-3 text-white-50">
                    <i class="fas fa-user"></i>
                </div>
                <div class="col-5">
                    <label class="text-info">
                        @Model.serviceHeaders[0].Car.ApplicationUser.Name
                    </label>
                    <br />
                    <label class="text-info">
                        @Model.serviceHeaders[0].Car.ApplicationUser.Email / @Model.serviceHeaders[0].Car.ApplicationUser.PhoneNumber
                    </label>
                </div>
                <div class="col-5">
                    <label class="text-info">
                        @Model.serviceHeaders[0].Car.Model / @Model.serviceHeaders[0].Car.Color
                    </label>
                    <br />
                    <label class="text-info">
                        @Model.serviceHeaders[0].Car.Name
                    </label>
                </div>
                <div class="col-1 text-center pt-3 text-white-50">
                    <i class="fas fa-car"></i>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            @Html.DisplayNameFor(m => m.serviceHeaders[0].Miles)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.serviceHeaders[0].TotalPrice)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.serviceHeaders[0].Description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.serviceHeaders[0].DateAdded)
                        </th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model.serviceHeaders)
                    {
                        <tr>
                            <td>@item.Miles</td>
                            <td class="text-success">@item.TotalPrice.ToString("#,0 تومان")</td>
                            <td>
                                @item.Description
                            </td>
                            <td>@item.DateAdded.ToShamsi()</td>
                            <td>
                                <a asp-page="Details" class="btn btn-info form-control"
                                   asp-route-serviceid="@item.Id">
                                    جزئیات
                                </a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
}